### ISSUE TITLE
Root folder name only coming. Browsing not working.

### ISSUE THREAD

**Issue by mahavishnup** [3x1io/filament-browser#5]
filament-browser.js:2 TypeError: Cannot read properties of undefined (reading 'length')
    at a.render (eval at fs (filament-browser.js:2:609201), <anonymous>:3:8201)
    at e._render (filament-browser.js:2:552095)
    at a.r (filament-browser.js:2:585217)
    at wn.get (filament-browser.js:2:543486)
    at new wn (filament-browser.js:2:543404)
    at filament-browser.js:2:585231
    at Mn.$mount (filament-browser.js:2:585378)
    at Mn.$mount (filament-browser.js:2:611034)
    at init (filament-browser.js:2:536239)
    at filament-browser.js:2:573512

**Comment by fadymondy** [comment]
some here #4
